#!/bin/bash

rm -rf *.ipk *.deb
find . -name '*~' -delete

### Build AREDN package
export COPYFILE_DISABLE=1
export VERSION=0.4

# Main
rm -rf data.tar.gz control.tar.gz
cd src/data
tar cf ../../data.tar `find . -type f | grep -v DS_Store | grep -v .pl | grep -v .pm`
cd ../control
sed -i "s/^Version: .*$/Version: ${VERSION}/" control
tar cfz ../../control.tar.gz .
cd ../..
gzip data.tar
COPYFILE_DISABLE=1 tar cfz port-config_${VERSION}_all.ipk control.tar.gz data.tar.gz debian-binary

rm -rf data.tar.gz control.tar.gz *.deb
