#!/bin/sh

sed -i -e '/\/cgi-bin\/advancednetwork:root:\$p\$root/d' /etc/httpd.conf
echo "/cgi-bin/advancednetwork:root:\$p\$root" >> /etc/httpd.conf

echo ""
echo "Configure advanced network optiions here:"
echo ""
echo "http:[NODENAME]/cgi-bin/advancednetwork"
echo ""
echo "Please reboot node to update page permissions!!"

exit 0
