#!/bin/sh

sed -i -e '/\/cgi-bin\/port-config:root:\$p\$root/d' /etc/httpd.conf
echo "/cgi-bin/port-config:root:\$p\$root" >> /etc/httpd.conf

echo ""
echo "Reconfigure device ports at:"
echo ""
echo "http:[NODENAME]/cgi-bin/port-config"
echo ""
echo "Please reboot node to update page permissions!!"

exit 0
